habilidades = [
    ["Abrir cerraduras", 0, false],
    ["Artesania", 0, false],
    ["Averiguar intenciones", 0, false],
    ["Avistar", 0, false],
    ["Buscar", 0, false],
    ["Concentracion", 0, false],
    ["Conocimiento de conjuros", 0, false],
    ["Descrifrar escritura", 0, false],
    ["Diplomacia", 0, false],
    ["Disfrazarse", 0, false],
    ["Engañar", 0, false],
    ["Equilibrio", 0, false],
    ["Escapismo", 0, false],
    ["Esconderse", 0, false],
    ["Escuchar", 0, false],
    ["Falsificar", 0, false],
    ["Interpretar", 0, false],
    ["Intimidar", 0, false],
    ["Inutilizar mecanismo", 0, false],
    ["Juego de manos", 0, false],
    ["Montar", 0, false],
    ["Moverse sigilosamente", 0, false],
    ["Nadar", 0, false],
    ["Oficio", 0, false],
    ["Piruetas", 0, false],
    ["Reunir informacion", 0, false],
    ["Saber arcano", 0, false],
    ["Saber arquitectura e ingenieria", 0, false],
    ["Saber dungeons", 0, false],
    ["Saber geografia", 0, false],
    ["Saber historia", 0, false],
    ["Saber local", 0, false],
    ["Saber los planos", 0, false],
    ["Saber naturaleza", 0, false],
    ["Saber nobleza y realeza", 0, false],
    ["Saber religion", 0, false],
    ["Saltar", 0, false],
    ["Sanar", 0, false],
    ["Supervivencia", 0, false],
    ["Tasacion", 0, false],
    ["Trato con animales", 0, false],
    ["Trepar", 0, false],
    ["Usar objeto magico", 0, false],
    ["Uso de cuerdas", 0, false]
]
//El primer numero indica el rango máximo de la habilidad, el booleano que le sigue si es clásea o no.
module.exports = habilidades;