'use strict'
//Nombre, caracteristica, afectada por pen armadura, mod caract, rangos, mod varios, clasea o no.
//El orden de los númericos es el mismo que en la ficha de personaje oficial.
const habilidades = [
    ["Abrir cerraduras", "Des", false, 0, 0, 0, false],
    ["Artesania", "Int", false, 0, 0, 0, false],
    ["Averiguar intenciones", "Sab", false, 0, 0, 0, false],
    ["Avistar", "Sab", false, 0, 0, 0, false],
    ["Buscar", "Int", false, 0, 0, 0, false],
    ["Concentracion", "Con", false, 0, 0, 0, false],
    ["Conocimiento de conjuros", "Int", false, 0, 0, 0, false],
    ["Descrifrar escritura", "Int", false, 0, 0, 0, false],
    ["Diplomacia", "Car", false, 0, 0, 0, false],
    ["Disfrazarse", "Car", false, 0, 0, 0, false],
    ["Engañar", "Car", false, 0, 0, 0, false],
    ["Equilibrio", "Des", true, 0, 0, 0, false],
    ["Escapismo", "Des", true, 0, 0, 0, false],
    ["Esconderse", "Des", true, 0, 0, 0, false],
    ["Escuchar", "Sab", false, 0, 0, 0, false],
    ["Falsificar", "Int", false, 0, 0, 0, false],
    ["Interpretar", "Car", false, 0, 0, 0, false],
    ["Intimidar", "Int", false, 0, 0, 0, false],
    ["Inutilizar mecanismo", "Int", false, 0, 0, 0, false],
    ["Juego de manos", "Des", false, 0, 0, 0, false],
    ["Montar", "Des", false, 0, 0, 0, false],
    ["Moverse sigilosamente", "Des", true, 0, 0, 0, false],
    ["Nadar", "Fue", true, 0, 0, 0, false],
    ["Oficio", "Sab", false, 0, 0, 0, false],
    ["Piruetas", "Des", true, 0, 0, 0, false],
    ["Reunir informacion", "Car", false, 0, 0, 0, false],
    ["Saber arcano", "Int", false, 0, 0, 0, false],
    ["Saber arquitectura e ingenieria", "Int", false, 0, 0, 0, false],
    ["Saber dungeons", "Int", false, 0, 0, 0, false],
    ["Saber geografia", "Int", false, 0, 0, 0, false],
    ["Saber historia", "Int", false, 0, 0, 0, false],
    ["Saber local", "Int", false, 0, 0, 0, false],
    ["Saber los planos", "Int", false, 0, 0, 0, false],
    ["Saber naturaleza", "Int", false, 0, 0, 0, false],
    ["Saber nobleza y realeza", "Int", false, 0, 0, 0, false],
    ["Saber religion", "Int", false, 0, 0, 0, false],
    ["Saltar", "Fue", true, 0, 0, 0, false],
    ["Sanar", "Sab", false, 0, 0, 0, false],
    ["Supervivencia", "Sab", false, 0, 0, 0, false],
    ["Tasacion", "Int", false, 0, 0, 0, false],
    ["Trato con animales", "Car", false, 0, 0, 0, false],
    ["Trepar", "Fue", true, 0, 0, 0, false],
    ["Usar objeto magico", "Car", false, 0, 0, 0, false],
    ["Uso de cuerdas", "Des", false, 0, 0, 0, false]
]
//El primer numero indica el rango máximo de la habilidad, el booleano que le sigue si es clásea o no.
module.exports = habilidades;